### ISSUE TITLE
Scope out the infrastructure for this from the simpy core library

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/aika#1]
Goal is performant Discrete Event Simulator
This will unblock the time issue in arbiter

**Comment by 0xJepsen** [comment]
Should scope from this: https://realpython.com/simpy-simulating-with-python/, and this core library https://gitlab.com/team-simpy/simpy

**Comment by 0xJepsen** [comment]
I think the core things are going to be the utilization of generators or co-processor which are making it into rust std:lib

**Comment by FiberedSkies** [comment]
I'm going to close this, the scope of aika is already significantly matching simpy in the areas that matter
